name: Deploy Functions
on:
  push:
    paths:
      - 'functions/**/*'
      - '.github/workflows/functions.workflow.yml'
jobs:
  deploy:
    if: contains(github.ref, 'master')
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          npm ci
          npm install firebase-tools
          npm --prefix functions ci
          npm --prefix functions run build
      - name: Set project
        run: npm run firebase -- use jaspero-jms --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: Detect file changes
        id: changes
        run: |
          files=`node ./.github/utils/function-changes.js '${{ steps.file_changes.outputs.files_modified}}' '${{ steps.file_changes.outputs.files_added}}'`
          echo '::set-output name=CHANGES::$files'
      - name: Deploy
        if: ${{ steps.changes.outputs.CHANGES }}
        run: npm run firebase -- deploy --only $FILES --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FILES: ${{ steps.changes.outputs.CHANGES }}
