name: Deploy Functions
on:
  push:
    paths:
      - 'functions/**/*'
      - '.github/workflows/functions.workflow.yml'
jobs:
  deploy:
    if: contains(github.ref, 'master')
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          npm ci
          npm install firebase-tools
          npm --prefix functions ci
          npm --prefix functions run build
      - name: Set project
        run: npm run firebase -- use jaspero-jms --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: Deploy to Firebase
#        if: ${{ github.event_name == 'pull_request' && github.event.action == 'unassigned' }}
        run: |
          files=`node ./.github/utils/function-changes.js '${{ steps.file_changes.outputs.files_modified}}' '${{ steps.file_changes.outputs.files_added}}'`
          npm run firebase -- deploy --only functions:$files --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
