name: Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install, build
        run: |
          cd client
          npm install
          npm run build
      - name: run Lighthouse CI
        run: |
          cd client
          npm install -g @lhci/cli@0.4.x
          lhci autorun
