name: Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install Dependencies
        run: |
          npm --prefix client ci
      - name: Build
        run: |
          echo export const ENV_CONFIG=$PUBLIC_CONFIG > client/src/env-config.ts
          npm run build:cms
        env:
          PUBLIC_CONFIG: ${{ secrets.PUBLIC_CONFIG }}
      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.4.x
          lhci autorun --config=./client/lighthouserc.js
