name: Pull Request on Push
on:
  push:
    branches-ignore:
      - dev
      - main
jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    strategy:
      matrix:
        prefix: ['feat', 'fix', 'chore', 'hotfix']
    steps:
      - name: Pull Request - ${{ matrix.prefix }}/
        uses: vsoch/pull-request-action@1.0.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: '${{ matrix.prefix }}/'
          PULL_REQUEST_BRANCH: 'main'
